version: '3'
services:
  jupyter:
    # image: jupyter/datascience-notebook
    image: jupyter-pyspark:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/work  # Монтирование папки
    environment:
      - JUPYTER_TOKEN=mysecretpassword  # Пароль для доступа